### ISSUE TITLE
Fitting the SpaNorm model crashes R session with COSMX dataset

### ISSUE THREAD

**Issue by joaolsf** [bhuvad/SpaNorm#4]
Hi, very nice normalisation method! I wanted to try in a COSMX dataset with ~500K cells. I tested decreasing values of sample.p (0.25, 0.05, 0.01, 0.0025) to optimise speed but all of the tests crashed the R session. Peak RAM usage at over 120GB even when sample.p=0.0025. Is there a way to optimise RAM usage and runtime, as the fitting step was taking around half hour from start until crash? It seems a valuable tool to compare to other normalisation methods for spatial transcriptomics data.
Thank you!

**Comment by joaolsf** [comment]
Hi @bhuvad, thanks for taking the time in helping me. I understand what you say. I tested what you suggested and did not work. It still uses a lot of RAM. I am also having issues to install and use the package on a HPC. I think I will wait until there is a new version of the package with better efficiency.
Cheers,
Joao

**Comment by bhuvad** [comment]
Hi @joaolsf,

Just to help use when we tackle this issue, would you be able to provide me with the following information:

1. Dataset size (how many cells and genes).
2. Was the data loaded in memory or with a delayed backend (e.g., HDF5)?
3. When you tried the above approach of fitting the model first and then estimating the adjusted values, did you have an issue with the first step or the second one (or both)?
4. Did you use the default SpaNorm settings or did you opt for using a larger sampling for estimation.

Knowing this information will help me replicate the problem and see how best to handle the memory hungry elements. I hope we can come up with a solution fast enough for you and other users working on these huge datasets soon!

Cheers,
Dharmesh

**Comment by joaolsf** [comment]
1- Dataset size (how many cells and genes)

A bit more than 500K cells, 1,000 genes.

2- Was the data loaded in memory or with a delayed backend (e.g., HDF5)?

I use Rstudio, with the SPE object saved as .rds. That is how I load the object in R. Not sure If I am answering your question.

3- When you tried the above approach of fitting the model first and then estimating the adjusted values, did you have an issue with the first step or the second one (or both)?

I had an issue with the first step, fitting the model.

4- Did you use the default SpaNorm settings or did you opt for using a larger sampling for estimation.

I tested first by just copying the line you wrote in your first response. Then it failed. Then I tried again with sample.p = 0.01, 0.005...all failed.

**Comment by bhuvad** [comment]
Hi @joaolsf,

I performed a memory profiling (using the profvis package) using Xenium data I had available at hand and the memory footprint was ~4.1GB even when I fit the model on ~250 genes and ~30k (sample.p = 0.05, total = 572k cells) cells. When I ran it on ~5k and ~10k cells across ~700 genes in a CosMx panel (total 100k cells), the memory profiling showed maximum RAM usage of 10GB and 36GB respectively. This is analogous to you using sample.p = 0.01.

<p>
<img width="1362" alt="CosMx_5k_cells" src="https://github.com/user-attachments/assets/54e64feb-3c39-44ba-90d7-7245b77e084f">
<em>SpaNorm fit of a CosMx sample (100k cells) using sample.p = 0.05 (~5000 cells)</em>
</p>

<p>
<img width="1363" alt="CosMx_10k_cells" src="https://github.com/user-attachments/assets/c50f11dc-7315-4419-8fee-4f9dba31a9b6">
<em>SpaNorm fit of a CosMx sample (100k cells) using sample.p = 0.1 (~10000 cells)</em>
</p>

The profiling shows that the usage should be much lower. Likewise, computation time should be a lot lower when sampling fewer cells for the model fit. As such, I am not sure why your usage spikes up. I have submitted the package to Bioconductor and am hoping to have that released in the next release (Oct 2024). Please try installing the package again and giving it a shot. If the problem persists, I can guide you on how to perform the profiling on your end to figure out the issue. I am closing this issue for now but if you have any other information to show that there is another issue, please reach out again and I will re-open the issue.

Cheers,
Dharmesh
