### ISSUE TITLE
plotGeneExpression function not found

### ISSUE THREAD

**Issue by swaruplab** [bhuvad/SpaNorm#5]
When plotting gene-expression using the GitHub tutorial, function plotGeneExpression is not defined and I could not find it in the GitHub code. Please help.

**Comment by swaruplab** [comment]
```
HumanDLPFC = [SpaNorm](https://bhuvad.github.io/SpaNorm/reference/SpaNorm.html)(HumanDLPFC, adj.method = "pearson")
p_pearson = plotGeneExpression(HumanDLPFC, "MOBP") +
  [ggtitle](https://ggplot2.tidyverse.org/reference/labs.html)("Pearson")
```

**Comment by bhuvad** [comment]
Hi @swaruplab,

The plotting function we have in the vignette is just for demonstration purposes. It is not implemented as part of the package and is not dynamic enough to handle all possible use cases. You can find the source code for that in the vignette markdown document: https://github.com/bhuvad/SpaNorm/blob/de33b2d5357fa0bda20022c2dc9344cbde009734/vignettes/SpaNorm.Rmd#L47 

I have plans to implement a more generic plotting function and will push that later in the year. It is mostly ready but needs the final polishing touches. We aim to have it ready by the next bioconductor release that should be in a couple of months.

Cheers,
Dharmesh
