### ISSUE TITLE
Model on subset of genes

### ISSUE THREAD

**Issue by roanvanscheppingen** [bhuvad/SpaNorm#6]
Hi,

Thank you for developing SpaNorm, we are quite interested it it's use. 
Currently, I am using a spatialexperiment to run spanorm and have found that it's quite necessary to first reduce the features to features that are present in a substantial amount of cells. Therefore we use ~6K features of the 30K features we have. 

After running the models, the 6K features are normalised, but I want to be able to also scale the other features of the original Seurat. 
Is there a 'simple' scaling factor I can use on the original Seurat cells for normalisation?

**Comment by bhuvad** [comment]
Hi @roanvanscheppingen,

The SpaNorm model attempts to fit the observed expression of each gene at each location. As such, we can only adjust the genes that have been modelled. Unlike normalisation methods such as scran, that attempt to estimate a location/cell specific size factor that is used to adjust all genes, SpaNorm performs a gene and location/cell specific adjustment. We are working on approaches to make SpaNorm scale across all genes through computational speed-ups so hopefully, pre-filtering of genes will not be required for much longer. I would like to mention, however, that genes that are very lowly expressed will likely be erroneous considering the still up and coming technologies. As such, some level of prefiltering may be advisable regardless of whether you are able to fit the model to more genes. Keep an eye out for future developments though and I hope we are able to make this feature available to you soon!

Cheers,
Dharmesh
